### ISSUE TITLE
Submit DOI as "Final" does not update the "state" field of the profile

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-Plugins/mdm-plugin-digital-object-identifiers#13]
**Describe the bug**
If a Data Model has been submitted to generate a DOI, first in "draft" and then in "final", the `status` field in the profile is not updated to match this new state.

**To Reproduce**
From the UI:

1. Create a new Data Model
2. Create a DOI profile and save it
3. Make the Data Model public
4. Finalise the Data Model
5. Now submit the Data Model to the DOI system in a "Draft" submission state. Check that the profile field `status` now says "draft" and a `suffix` has been stored.
6. Now submit the Data Model as a final DOI.

**Expected behavior**
The profile should have been updated to record the `status` as "final".

**Screenshots**
The screenshot below shows the mismatch between what is stored in the profile and what is now returned by the `GET /api/{domainType}/{id}/doi` endpoint:

![image](https://user-images.githubusercontent.com/3219480/129381247-02585d61-1817-4845-b60e-0e58e3a9520a.png)

**Comment by pjmonks** [comment]
Latest testing has found that the change of status from "draft" to "findable" (final) now occurs. However, if you retire a DOI then the "Status" profile field does not update to reflect that.

To replicate, follow the steps described above but send a "Final" DOI so that the profile field is "findable". Then retire the DOI and notice that the profile field does not show the same as the `GET /api/{domainType}/{id}/doi` endpoint:

![image](https://user-images.githubusercontent.com/3219480/130244920-6e5a51c7-cd36-4f5d-848d-f4f7714bb0df.png)

**Comment by olliefreeman** [comment]
So we have a slight "mismatch" on information ....
the "state" in the profile is the state against datacite which can be one of
* draft
* findable
* hide
* registered

where 
* draft -> findable||registered
* findable -> hide

There is then our internal status which can be
 * draft
 * final
 * retired
 * not_applicable

* draft == draft
* final == findable
* retired == registered || hide
* not_applicable == not actually done anything yet

**Comment by olliefreeman** [comment]
Im willing to admit theres probably a bug somewhere in this, and we should probably reconfigure the profile info to show both their and our status and make sure that it all matches up.

**Comment by pjmonks** [comment]
![image](https://user-images.githubusercontent.com/3219480/130248060-71f61444-e310-4b20-bbcb-1a374630e38e.png)

The description on the `status` field says "retired" is a possible value, so there needs to be some consistency somewhere around this area.

**Comment by olliefreeman** [comment]
i agree
