### ISSUE TITLE
`DigitalObjectIdentifiersProfileProviderService` is not marked as can be edited after finalisation

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-Plugins/mdm-plugin-digital-object-identifiers#15]
Found an issue in `services/uk/ac/ox/softeng/maurodatamapper/plugins/digitalobjectidentifiers/profile/DigitalObjectIdentifiersProfileProviderService.groovy`. The super class method `canBeEditedAfterFinalisation()` is not overridden, meaning by default this returns `false`.

The result of this is that the `ProfileInterceptor` in `mdm-plugin-profiles` never enters the `if` condition:

![image](https://user-images.githubusercontent.com/3219480/130243835-45a8c1c4-4717-4cdd-849b-619d4aa2c9d0.png)

It is required for DOI profiles to allow to be edited after finalisation due to the workflow. Therefore this (at least) needs to be added to `DigitalObjectIdentifiersProfileProviderService`:

```groovy
@Override
Boolean canBeEditedAfterFinalisation() {
    true
}
```

**Comment by olliefreeman** [comment]
could have sworn i did this
